### ISSUE TITLE
v1.1.4 breaks SSHClient

### ISSUE THREAD

**Issue by primuslam** [airbnb/omniduct#101]
Hi all, 1.1.4 introduces the lazy memoization of `__connected`, which is set in `Duct.connect()` after successful call by subclass to `_connect()`.

Unfortunately, since `SSHClient._connect()` asserts `.is_connected()` before the end of the function (https://github.com/airbnb/omniduct/blob/v1.1.4/omniduct/remotes/ssh.py#L161), it's impossible to ever set `__connected` to true in `SSHClient`, making it somewhat unusable.

**Comment by primuslam** [comment]
Probably, the simplest fix is to remove the assert; is_connected() calls can wait until the connection is actually needed.

**Comment by matthewwardrop** [comment]
Thanks @primuslam and @naoyak . Will fix this imminently. Sorry for the delay!

**Comment by matthewwardrop** [comment]
Fixed in v1.1.5. Thanks for reporting this!
