### ISSUE TITLE
Plan for documentation

### ISSUE THREAD

**Issue by djKooks** [airbnb/omniduct#18]
Is there a plan for documentation? Because it is bit complicate to start over clearly.

**Comment by matthewwardrop** [comment]
Yes... documentation is planned. I plan to release 1.0.0 before the end of the year with unit-tests and documentation. In the mean time, if you have any questions, feel free to contact me.

**Comment by djKooks** [comment]
@matthewwardrop Okay thanks!!

**Comment by djKooks** [comment]
@matthewwardrop Is there some kind of simple use case of this module in your work? Because there are no sample and docs, it is complicate to start over it and I'm not sure that I'm doing it well.
Thanks.
