### ISSUE TITLE
How about setting up some example code?

### ISSUE THREAD

**Issue by djKooks** [airbnb/omniduct#22]
Hello.
How about add some example file, or setup in README file?
I'm trying to add some driver with other DB and try to make it fit with default duct, but I couldn't do it well because I'm not sure my test code are going right.

I think guide for API will take some time, so instead of that just sample anyone using currently could be great help.
Thanks.

**Comment by matthewwardrop** [comment]
Hi @djKooks ,

The best example code we have currently is probably the implementation for Hive and Presto. Beyond that, what would be helpful?

**Comment by djKooks** [comment]
@matthewwardrop Thanks for review.
I think it will be just find to show yours. What I just want to see is the process of code to access DB with `omniduct` APIs, no matter using which DB. It would be very helpful.
Thanks!

**Comment by matthewwardrop** [comment]
@djKooks You can see all the current implementations in the source code here: https://github.com/airbnb/omniduct/tree/master/omniduct/databases

**Comment by djKooks** [comment]
@matthewwardrop It is pretty good reference to add more DB, but giving a simple lines to preview how `duct` could be used for implementation will be good to tell clear concept of this project.
I think #24 is good. How do you think?

**Comment by matthewwardrop** [comment]
Merged. I'll close this issue for now, but I definitely am aware that more documentation is necessary :).
