### ISSUE TITLE
Add on test case

### ISSUE THREAD

**Issue by djKooks** [airbnb/omniduct#29]
Hello.
Do you have a plan for updating test cases? If so, I just want to know how you are going to make and attach to CI process(currently in travis).
Also, how do you make a test case which need to be access on database? As I know database package should be installed for using it in test case, and it means it will be needed to be added in travis script too. Am I right?
I'm not quite good on this, so If you have some experience about it, please let me know.

Thanks.

**Comment by matthewwardrop** [comment]
Hi @djKooks . When we get around to it, we will be adding a testsuite that both sets up and then tests against real databases. You can see examples for how this might be done over at http://github.com/dropbox/pyhive.

**Comment by djKooks** [comment]
@matthewwardrop Thanks! I'll refer on this case.
