### ISSUE TITLE
Druid Connection

### ISSUE THREAD

**Issue by danfrankj** [airbnb/omniduct#50]
@matthewwardrop the druid db in omniduct is a Connection() object which does not support setting username and password, resulting in a method not found when we try set_basic_auth_credentials.  Are you OK if I just log a warning until there is some way to fix this in pydruid? 

https://github.com/druid-io/pydruid/blob/125a2d7e9e6661c9e78c58669049bf35f0ec0b7c/pydruid/db/api.py#L90

**Comment by matthewwardrop** [comment]
@danfrankj  Whoops! I must have conflated the client with the raw connection used here. Go ahead and roll back my changes here, posting a warning as you suggest. Sorry!
