### ISSUE TITLE
Access problem in hiveserver2

### ISSUE THREAD

**Issue by djKooks** [airbnb/omniduct#53]
Hello,
It seems my hiveserver2 client sample does not working well. Could you look on?
```
from omniduct.databases.hiveserver2 import HiveServer2Client
vb_host = '192.168.56.1'
vb_port = 22

hsc = HiveServer2Client(host=vb_host, port=vb_port, driver='impyla')
hsc.is_connected()  # return false
```
Am I doing something wrong?
If you have some simple example, please share it.

Thanks.

**Comment by matthewwardrop** [comment]
Hi @djKooks,

It looks like you're directing the `HiveServer2Client` to the SSH port of the remote service, which is almost certainly not what you want to do. Do you have a HiveServer2 instance running?

**Comment by djKooks** [comment]
@matthewwardrop thanks for reply.
Yes, I'm trying to access hive in remote machine(virtualbox instance). If my usage is wrong, please let me know.

Thanks.

**Comment by matthewwardrop** [comment]
If the remote machine has a hiveserver2 instance, and the ports associated with the instance are exposed, you can just directly connect to it.

```
from omniduct.databases.hiveserver2 import HiveServer2Client

hsc = HiveServer2Client(
    host='192.168.56.1',  # IP address of virtual machine 
    port=3623,  # Port of HiveServer2 instance (typically 3623)
    driver='pyhive'  # Recommended over impyla
)

hsc.connect()
```

If the HiveServer2 instance is not exposed, then you will need to use port-forwarding via SSH.

```
from omniduct.databases.hiveserver2 import HiveServer2Client
from omniduct.remotes.ssh import SSHClient

remote = SSHClient(
     host='192.168.56.1',  # IP address of virtual machine 
     port=22,  # Port of SSH server
)

hsc = HiveServer2Client(
    host='127.0.0.1',  # IP address of localhost 
    port=3623,  # Port of HiveServer2 instance (typically 3623)
    remote=remote
)

hsc.connect()
```

Hope that helps.

**Comment by djKooks** [comment]
@matthewwardrop thanks! I'll check again later and let you know.

**Comment by djKooks** [comment]
@matthewwardrop sorry for late.
It seems it is problem of hive server connection, because it also causes on other modules such as pyhive or impyla. 
I'll reopen it if I found a problem in here.

Thanks.
