### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by djKooks** [airbnb/omniduct#66]
Hello.
I'm working with some protocol, and trying to add as example. Currently, there are only few examples in document(and only for `Presto`), it seems good to add more.

To add on, which way will be good to add on project?
- In document
- Making new example directory, and add as python file
- Making new example directory, and add as jupyter notebook file

How do you think?

Thanks.

**Comment by naoyak** [comment]
@djKooks it'd be great if we had more examples in the docs - I think adding them to https://github.com/airbnb/omniduct/blob/master/docs/quickstart.rst would be fine for now, and then if it starts getting cluttered we can think about reorganizing. Did you have any specific examples in mind?

**Comment by djKooks** [comment]
@naoyak thanks for comment! Okay, than I'll update in that way.
But as you see, example for `presto` is very long, so maybe it could be better to split quickstart page by protocol(or by task). Do you have suggestions?

`Did you have any specific examples in mind?`:
Yes. It is not complicate example, but just to show basic usage for other protocols(for mysql, hdfs, druid, etc.)

**Comment by naoyak** [comment]
Yeah, I suppose we could start a `docs/examples` directory and create separate pages by task. Feel free to submit a PR! @matthewwardrop might have some ideas too.

**Comment by djKooks** [comment]
@naoyak okay~I'll start based on your suggestion.

**Comment by matthewwardrop** [comment]
Closing this issue in favour of continued discussion in #67 :).
