### ISSUE TITLE
REST implement put and post the data ?

### ISSUE THREAD

**Issue by harsham4026** [airbnb/omniduct#78]

**Comment by harsham4026** [comment]
@matthewwardrop I was thinking if we can implement the put and post methods in RestClientBase for posting the data to given REST API. Let me know if we need or not needed to implement these things.

**Comment by matthewwardrop** [comment]
@harsham4026 Greetings again! Post and put are already implemented: https://github.com/airbnb/omniduct/blob/master/omniduct/restful/base.py#L49; just pass `method='post'`.
