### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by danfrankj** [airbnb/omniduct#85]
@matthewwardrop  would be good to get omni listed in airbnb's OS tools page (https://airbnb.io/): https://github.com/airbnb/airbnb.github.io but I think we need a logo first. I gave a stab at it. Thoughts?

![image](https://user-images.githubusercontent.com/616139/47626452-6d8c9e00-dae8-11e8-95d6-5d40c2940c21.png)

**Comment by matthewwardrop** [comment]
@danfrankj This looks pretty neat. I came up with a series of designs earlier, one of which was like a fractal of nested pipes, but I think this looks much simpler and cleaner. I'd like to play around with some colours... do you have the SVG source?

**Comment by danfrankj** [comment]
@matthewwardrop 
Looks like github won't upload svg but this should work
https://www.dropbox.com/s/13btv5a2spzopbv/omni_logo.svg?dl=0

**Comment by matthewwardrop** [comment]
@danfrankj I played around with things a bit, and ended up with a new concept. What do you think of this?
![omniduct](https://user-images.githubusercontent.com/124910/48641494-d13f1400-e98e-11e8-9a49-d2a1aff376ca.png)

**Comment by matthewwardrop** [comment]
@danfrankj I had thought this 2D enough... I mean, it is 2D with just a little shading. As you shrink it down it remains recognisable.

The current design is that of an "omni" duct ( the thing with an eye ) with other ducts passing into it. A duck kind of loses that meaning... And would be harder to draw ;).

**Comment by danfrankj** [comment]
Ok fine, omniduck is a bad pun idea. 

How about a bit more duct'y. 

![image](https://user-images.githubusercontent.com/616139/48666894-51dd3d80-ea7f-11e8-96bb-d72bf89d0dc8.png)

**Comment by danfrankj** [comment]
I do like the 2D version better. How about trying to combine these ideas a bit?

![image](https://user-images.githubusercontent.com/616139/48991964-58f0f500-f0ea-11e8-85df-36fd1e72647c.png)

**Comment by matthewwardrop** [comment]
@danfrankj I like it. I think icons should probably be square, so that they fit nicely into other UIs, and have at least ~50% pixel coverage... so... how does this look to you?
![g4101](https://user-images.githubusercontent.com/124910/49174060-37665800-f2fa-11e8-8cb7-bb8a521e3ce7.png)

**Comment by danfrankj** [comment]
like it @matthewwardrop . 🚢-it !!!

**Comment by matthewwardrop** [comment]
Thanks for helping to make the icon awsome.
