### ISSUE TITLE
Plan to support DB in cloud service?

### ISSUE THREAD

**Issue by djKooks** [airbnb/omniduct#9]
Hello. It looks like a project with good concept. Nice to see it.
Just one question about roadmap. Does it have a plan to have a connector for DB on cloud service, such as DynamoDB or else?

Thanks.

**Comment by matthewwardrop** [comment]
Hi @djKooks,

Since we don't need to connect to this service internally, there are no immediate plans to support this, but we welcome patches supporting connectors to other services. Writing a new connector is reasonably straightforward, but if you need help, don't hesitate to reach out.

**Comment by djKooks** [comment]
@matthewwardrop Thanks!
